### ISSUE TITLE
Webhook address silently unsubscribing

### ISSUE THREAD

**Issue by SpaceDandy** [MicrosoftDocs/office-365-management-api#179]
So I have some subscriptions to content from an app I've created. 

`[
    {
        "contentType": "Audit.AzureActiveDirectory",
        "status": "enabled",
        "webhook": null
    },
    {
        "contentType": "Audit.Exchange",
        "status": "enabled",
        "webhook": {
            "authId": "rvUCHW2N5u1H0mjo7XPOL0JCSum68g",
            "address": "https://api.elevatesecurity.com/customer-integrations/webhook/elevate/fny5DEz2qSK4pIqfTYykscFi27xTO7",
            "expiration": "",
            "status": "enabled"
        }
    },
    {
        "contentType": "Audit.General",
        "status": "enabled",
        "webhook": {
            "authId": "FU4hIefAL5Tf98NJnSLbzkunYgEyBw",
            "address": "https://api.elevatesecurity.com/customer-integrations/webhook/elevate/diDF58FMDShIx5faEl78m4HnUIQb9N",
            "expiration": "",
            "status": "enabled"
        }
    },
    {
        "contentType": "Audit.SharePoint",
        "status": "enabled",
        "webhook": {
            "authId": "aAwTBrtOJ10Ur0m-bKU-wnLL51PUFQ",
            "address": "https://api.elevatesecurity.com/customer-integrations/webhook/elevate/zyZtjAFYmX6QgXqbmiRWpuo9YMUtDT",
            "expiration": "",
            "status": "enabled"
        }
    },
    {
        "contentType": "DLP.All",
        "status": "enabled",
        "webhook": null
    }
]`

For some reason aside from the initial validation ping to the webhook address, I never get any more traffic to the webhook and at some point the address will unsubscribe. 

I guess my questions are:

What are causes for an un subbing for webhook address? 

Can I check for outbound webhook traffic to see if content was pushed to me?

Can a tenant have multiple webhook addresses or subscriptions to content open?

Is there an issue on your end?

**Comment by SpaceDandy** [comment]
Also just received 3 HEAD requests on my webhooks...

**Comment by markjjo** [comment]
@SpaceDandy It's possible that this is related to this service advisory: 

All admins unable to see audit log results for July 25, 2020, or later, in the Security and Compliance Center (SCC)
EX220132, Exchange Online, Last updated: August 13, 2020 12:58 PM
Start time: August 6, 2020 8:59 AM

You can view in M365 admin center (Health > Service Health > Advisories) - Looks like issue is related to code change: 

Root cause: A recent settings change to increase audit logging threshold limits resulted in erroneous logs being generated, which is preventing admins from seeing audit log results for July 25, 2020, or later in the SCC.

Otherwise, you can open ticket with MS Support.

**Comment by SpaceDandy** [comment]
Weird I dont even see that advisory...
